import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Image from "next/image";

export default function Home( {data} ) {
  return (
    <>
      <Head>
        <title>Event App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <header>
          <nav>
            <img />
            <a href="/">Home</a>
            <a href="/events">Events</a>
            <a href="/about-us">About Us</a>
          </nav>
        </header>
        
        <main className={styles.main}>
          { data.map(ev => <a key={ev.id} href={`/events/${ev.id}`}>
            <Image alt={ev.title} width={300} height={300} src={ev.image} /> 
            <h2>{ev.title}</h2> 
            <p>{ev.description}</p></a>) }
            
        </main>
        <footer className={styles.footer}>
          <p>@ 2025 Event App</p>
        </footer>
      </>
  );
}

export async function getServerSideProps ()  {
  const { events_categories } = await import ('/data/data.json');
  //console.log(events_categories);
 
  return{
    props: {
      data: events_categories,
    }
  }
}
